### PR TITLE
Split EntityList logic (Tests & Test Suites)

### PR DESCRIPTION
**Pull request by rangoo94**
This PR is trying to extract the abstract logic from the EntityList page, that was handling both Tests and Test Suites.
There may be still another stage of improving that, yet it already has decoupled a lot, reducing its code by half, and works well as such.

## Changes

- **Note: it may be easier to check this PR commit by commit - it has been iteratively decoupling these pages, so it's easier to understand the reasoning this way**
- Prepare specific `TestsList` and `TestSuitesList` pages, instead of the `EntityListBlueprint`
- Avoid all the related configuration files and data layer
- use `ModalContext` instead of local `Modal`
- avoid adding `testIcon` property into the Test - compute it dynamically
- Delete unused or unnecessary code
- Simplify deep-linking logic (filters in the URL) - handle it fully in `EntityListContent`

## Fixes

- part of https://github.com/kubeshop/testkube/issues/3958

## How to test it

-

## screenshots

-

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by Toxer10 — APPROVED** [review]

**Comment by rangoo94** [comment]
> Filters is supposed to be remain when you refresh, or paste a link with them applied. I see it has been removed in this PR, is it meant to happen?

It worked fine for the production build, it wasn't working for the `StrictMode` available for development. Fixed now 👍

**Review by pavloburchak — APPROVED** [review]

**Comment by pavloburchak** [comment]
image
Abort option looks not really great when the item is on the right

**Comment by pavloburchak** [comment]
Also according abortion, I am not sure it is a great idea to display this option when there are no running executions. I click on it and nothing happens

**Comment by rangoo94** [comment]
> Also according abortion, I am not sure it is a great idea to display this option when there are no running executions. I click on it and nothing happens

@fivenp, what do you think about it?

**Comment by fivenp** [comment]
I think: https://github.com/kubeshop/testkube/issues/3988 :)

**Pull request merged**
